{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Unit Testing\n",
    "## Exceptions\n",
    "### Exception Introduction\n",
    "**SyntaxError** is raised when the parser encounters a syntax error.\n",
    "```text\n",
    "  File \"script.py\", line 1\n",
    "    def print_five\n",
    "                 ^\n",
    "SyntaxError: invalid syntax\n",
    "```\n",
    "**Exceptions** are raised when the program encounters an error during its execution.\n",
    "```text\n",
    "Traceback (most recent call last):\n",
    "  File \"script.py\", line 1, in <module>\n",
    "    print(1/0)\n",
    "ZeroDivisionError: division by zero\n",
    "```\n",
    "### Built-in Exceptions\n",
    "Most exceptions inherit from the `BaseException` class, which inherits from the `Exception` class. The `Exception` class is the base class for all built-in exceptions. You can find a list of built-in exceptions [here](https://docs.python.org/3/library/exceptions.html).\n",
    "\n",
    "There's a lot of built-in exceptions, but we don't need to know all of them. We just need to know the most common ones.\n",
    "\n",
    "### Raising Exceptions\n",
    "- Syntax\n",
    "```python\n",
    "raise NameError\n",
    "# or \n",
    "raise NameError('Custom Message')\n",
    "```\n",
    "- Here's an example of raising a `TypeError` exception:\n",
    "```python\n",
    "def open_register(employee_status):\n",
    "  if employee_status == 'Authorized':\n",
    "    print('Successfully opened cash register')\n",
    "  else:\n",
    "    # Alternatives: raise TypeError() or TypeError('Message')\n",
    "    raise TypeError\n",
    "```\n",
    "- Alternatively, when no built-in exception fits the error, it might be better to use a generic exception with a custom message:\n",
    "```python\n",
    "def open_register(employee_status):\n",
    "  if employee_status == 'Authorized':\n",
    "    print('Successfully opened cash register')\n",
    "  else:\n",
    "    raise Exception('Employee does not have access!')\n",
    "```\n",
    "### Try/Except\n",
    "- Python will first attempt to execute the code inside the `try` block.\n",
    "- If an exception is raised, Python will stop executing the `try` block and jump to the `except` block.\n",
    "- If no exception is raised, the `except` block will be skipped.\n",
    "- The `finally` block will always be executed, regardless of whether an exception was raised."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "The hex value of red is #FF0000\n",
      "Loop continues...\n",
      "An exception occurred! Color does not exist.\n",
      "Loop continues...\n",
      "The hex value of yellow is #FFFF00\n",
      "Loop continues...\n"
     ]
    }
   ],
   "source": [
    "colors = {\n",
    "    'red': '#FF0000',\n",
    "    'blue': '#0000FF',\n",
    "    'yellow': '#FFFF00',\n",
    "}\n",
    "\n",
    "for color in ('red', 'green', 'yellow'):\n",
    "  try:\n",
    "    print('The hex value of ' + color + ' is ' + colors[color])\n",
    "  except:\n",
    "    print('An exception occurred! Color does not exist.')\n",
    "  print('Loop continues...')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Catching Specific Exceptions\n",
    "It is considered bad practice to catch all exceptions. Instead, you should catch specific exceptions. This way, you can handle different exceptions in different ways.\n",
    "\n",
    "- You can catch specific exceptions by specifying the exception type after the `except` keyword.\n",
    "- If you don't specify an exception type, the `except` block will catch all exceptions.\n",
    "\n",
    "```python\n",
    "try:\n",
    "    print(undefined_var)\n",
    "except NameError:\n",
    "    print('We hit a NameError')\n",
    "```\n",
    "Python allows us to capture the exception object by using the `as` keyword."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "We hit a NameError\n",
      "name 'undefined_var' is not defined\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    print(undefined_var)\n",
    "except NameError as errorObject:\n",
    "    print('We hit a NameError')\n",
    "    print(errorObject)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Handling Multiple Exceptions\n",
    "```python\n",
    "try:\n",
    "    # Some code to try!\n",
    "except (NameError, ZeroDivisionError) as e:\n",
    "    print('We hit an Exception!')\n",
    "    print(e)\n",
    "```\n",
    "\n",
    "We can also handle multiple exceptions by using multiple `except` blocks.\n",
    "\n",
    "```python\n",
    "try:\n",
    "    # Some code to try!\n",
    "except NameError:\n",
    "    print('We hit a NameError Exception!')\n",
    "except KeyError:\n",
    "    print('We hit a TypeError Exception!')\n",
    "except Exception:\n",
    "    print('We hit an exception that is not a NameError or TypeError!')\n",
    "```\n",
    "**Note:** The order of the `except` blocks is important. Python will execute the first block that matches the exception. The last block should always be a generic exception block.\n",
    "\n",
    "### The `else` Clause\n",
    "The `else` clause will be executed if no exceptions are raised.\n",
    "\n",
    "```python\n",
    "try:\n",
    "  check_password()\n",
    "except ValueError:\n",
    "  print('Wrong Password! Try again!')\n",
    "else:\n",
    "  login_user()\n",
    "  # 20 other lines of imaginary code\n",
    "```\n",
    "The use of `else` is better than putting all the code inside the `try` block. It makes the code cleaner and easier to read.\n",
    "\n",
    "```python\n",
    "try:\n",
    "  check_password()\n",
    "  login_user()\n",
    "  # 20 other lines of imaginary code\n",
    "except ValueError:\n",
    "  print('Wrong Password! Try again!')\n",
    "```\n",
    "The `ValueError` could occur in the `login_user()` function, but the error message would be misleading.\n",
    "\n",
    "### The `finally` Clause\n",
    "The `finally` clause will always be executed, regardless of whether an exception was raised.\n",
    "\n",
    "```python\n",
    "try:\n",
    "  check_password()\n",
    "except ValueError:\n",
    "  print('Wrong Password! Try again!')\n",
    "else:\n",
    "  login_user()\n",
    "  # 20 other lines of imaginary code\n",
    "finally:\n",
    "  load_footer()\n",
    "```\n",
    "Since the footer is always loaded, it should be in the `finally` block.\n",
    "\n",
    "```python\n",
    "try:\n",
    "    check_password()\n",
    "finally:\n",
    "    load_footer()\n",
    "    # Other code we always want to run \n",
    "```\n",
    "It can be used independently without the `except` and `else` blocks. This is a convenient way to ensure that certain code is always executed.\n",
    "\n",
    "### User-defined Exceptions\n",
    "```python\n",
    "class CustomError(Exception):\n",
    "    pass\n",
    "```\n",
    "By convention, user-defined exceptions should end with the word `Error`.\n",
    "\n",
    "```python\n",
    "class LocationTooFarError(Exception):\n",
    "   pass\n",
    "\n",
    "def schedule_delivery(distance_from_store):\n",
    "    if distance_from_store > 10:\n",
    "        raise LocationTooFarError\n",
    "    else:\n",
    "        print('Scheduling the delivery...')\n",
    "```\n",
    "### Customizing User-defined Exceptions\n",
    "```python\n",
    "class LocationTooFarError(Exception):\n",
    "   def __init__(self, distance):\n",
    "       self.distance = distance\n",
    "       \n",
    "   def __str__(self):\n",
    "        return 'Location is not within 10 km: ' + str(self.distance)\n",
    "\n",
    "def schedule_delivery(distance_from_store):\n",
    "    if distance_from_store > 10:\n",
    "        raise LocationTooFarError(distance_from_store)\n",
    "    else:\n",
    "        print('Scheduling the delivery...')\n",
    "```\n",
    "The `__str__` method is called when the exception is raised. It returns a string representation of the exception.\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Unit Testing\n",
    "### Introduction to Testing\n",
    "**Unit Testing** is a software testing method by which individual units of source code are tested to determine whether they are fit for use. A unit is the smallest testable part of any software. It usually has one or a few inputs and usually a single output.\n",
    "\n",
    "Testing generally be divided into two categories:\n",
    "- **Manual Testing**: This is the process of manually testing software for defects. It requires a tester to play the role of an end user and use most of all features of the application to ensure correct behavior.\n",
    "- **Automated Testing**: This is the process of testing the software using an automation tool. It is used to write and execute test cases. It is faster, reliable, and more efficient than manual testing.\n",
    "\n",
    "### The `assert` Statement\n",
    "The `assert` statement is used to check if a condition is `True`. If the condition is `False`, the program will raise an `AssertionError` with an optional error message.\n",
    "\n",
    "```text\n",
    "assert <condition>, 'Message if condition is not met'\n",
    "```"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "ename": "AssertionError",
     "evalue": "Expected times_ten(20) to return 200, instead got 2000",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mAssertionError\u001b[0m                            Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[1], line 5\u001b[0m\n\u001b[1;32m      2\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m number \u001b[38;5;241m*\u001b[39m \u001b[38;5;241m100\u001b[39m\n\u001b[1;32m      4\u001b[0m result \u001b[38;5;241m=\u001b[39m times_ten(\u001b[38;5;241m20\u001b[39m)\n\u001b[0;32m----> 5\u001b[0m \u001b[38;5;28;01massert\u001b[39;00m result \u001b[38;5;241m==\u001b[39m \u001b[38;5;241m200\u001b[39m, \u001b[38;5;124m'\u001b[39m\u001b[38;5;124mExpected times_ten(20) to return 200, instead got \u001b[39m\u001b[38;5;124m'\u001b[39m \u001b[38;5;241m+\u001b[39m \u001b[38;5;28mstr\u001b[39m(result)\n",
      "\u001b[0;31mAssertionError\u001b[0m: Expected times_ten(20) to return 200, instead got 2000"
     ]
    }
   ],
   "source": [
    "def times_ten(number):\n",
    "    return number * 100\n",
    "\n",
    "result = times_ten(20)\n",
    "assert result == 200, 'Expected times_ten(20) to return 200, instead got ' + str(result)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "An `assert` statement is a quick way to test code during development. It is not a replacement for proper unit testing.\n",
    "\n",
    "### Unit Testing\n",
    "A test validates that the code is working as expected. It is a piece of code that checks the correctness of another piece of code.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "# The unit we want to test\n",
    "def times_ten(number):\n",
    "    return number * 10\n",
    "\n",
    "# A unit test function with a single test case\n",
    "def test_multiply_ten_by_zero():\n",
    "    assert times_ten(0) == 0, 'Expected times_ten(0) to return 0'"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "A common approach is to create test cases for specific edge cases. An edge case is a scenario that is not commonly encountered and may cause the program to crash."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "def test_multiply_ten_by_one_million():\n",
    "    assert times_ten(1000000) == 10000000, 'Expected times_ten(1000000) to return 10000000'\n",
    "\n",
    "def test_multiply_ten_by_negative_number():\n",
    "    assert times_ten(-10) == -100, 'Expected times_ten(-10) to return -100'"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "We can create a many test cases for a single function. Each test case should test a different scenario.\n",
    "\n",
    "### Python's `unittest` Framework\n",
    "\n",
    "The previous examples were simple and easy to understand, but they are not scalable. As the codebase grows, it becomes harder to manage the tests. Python's `unittest` framework provides a more organized way to write tests.\n",
    "\n",
    "Let's refactor the previous examples using the `unittest` framework.\n",
    "\n",
    "```python\n",
    "import unittest \n",
    "\n",
    "class TestTimesTen(unittest.TestCase):\n",
    "    pass\n",
    "```\n",
    "The `unittest` framework requires us to create a class that inherits from `unittest.TestCase`. Each test is a method that starts with the word `test`.\n",
    "\n",
    "```python\n",
    "import unittest\n",
    "\n",
    "class TestTimesTen(unittest.TestCase):\n",
    "    def test_multiply_ten_by_zero(self):\n",
    "        pass\n",
    "\n",
    "    def test_multiply_ten_by_one_million(self):\n",
    "        pass\n",
    "\n",
    "    def test_multiply_ten_by_negative_number(self):\n",
    "        pass\n",
    "```\n",
    "The `unittest` framework will automatically run all methods that start with the word `test`.\n",
    "\n",
    "```python\n",
    "import unittest\n",
    "\n",
    "class TestTimesTen(unittest.TestCase):\n",
    "    def test_multiply_ten_by_zero(self):\n",
    "        self.assertEqual(times_ten(0), 0, 'Expected times_ten(0) to return 0')\n",
    "\n",
    "    def test_multiply_ten_by_one_million(self):\n",
    "        self.assertEqual(times_ten(1000000), 10000000, 'Expected times_ten(1000000) to return 10000000')\n",
    "\n",
    "    def test_multiply_ten_by_negative_number(self):\n",
    "        self.assertEqual(times_ten(-10), -100, 'Expected add_times_ten(-10) to return -100')\n",
    "```\n",
    "Lastly, we need to change the `assert` statements to `self.assertEqual` and call the `unittest.main()` method to run the tests.\n",
    "\n",
    "```python\n",
    "# Run the tests\n",
    "unittest.main()\n",
    "```"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Assert Methods I: Equality and Membership\n",
    "\n",
    "| Method                | Equivalent        |\n",
    "|-----------------------|-------------------|\n",
    "| self.assertEqual(2, 5) | assert 2 == 5    |\n",
    "| self.assertIn(5, [1, 2, 3]) | assert 5 in [1, 2, 3] |\n",
    "| self.assertTrue(0)   | assert bool(0) is True |\n",
    "\n",
    "### Assert Methods II: Quantitative Methods\n",
    "\n",
    "| Method                        | Equivalent               |\n",
    "|------------------------------|--------------------------|\n",
    "| self.assertLess(2, 5)        | assert 2 < 5            |\n",
    "| self.assertAlmostEqual(.22, .225) | assert round(.22 - .225, 7) == 0 |\n",
    "\n",
    "The `assertAlmostEqual` method checks that the difference between two numbers, when rounded to 7 decimal places, is zero. In this case, the test will pass.\n",
    "\n",
    "### Assert Methods III: Exception and Warning Methods\n",
    "\n",
    "- self.assertRaises(specificException, function, functionArguments...)\n",
    "- self.assertWarns(specificWarning, function, functionArguments...)\n",
    "\n",
    "Complete List: [unittest](https://docs.python.org/3/library/unittest.html#unittest.TestCase.debug)\n",
    "\n",
    "### Parameterizing Tests\n",
    "By parameterizing tests, we can run the same test with different inputs. This is useful when we have many test cases that follow the same pattern.\n",
    "\n",
    "```python\n",
    "import unittest\n",
    "\n",
    "# The function we want to test\n",
    "def times_ten(number):\n",
    "    return number * 100\n",
    "\n",
    "# Our test class\n",
    "class TestTimesTen(unittest.TestCase):\n",
    "    \n",
    "    # A test method\n",
    "    def test_times_ten(self):\n",
    "        for num in [0, 1000000, -10]:\n",
    "            with self.subTest():\n",
    "                expected_result = num * 10\n",
    "                message = 'Expected times_ten(' + str(num) + ') to return ' + str(expected_result)\n",
    "                self.assertEqual(times_ten(num), expected_result, message)\n",
    "```\n",
    "The `subTest` method allows us to run the same test with different inputs. If the test fails, the `subTest` method will provide more information about which input caused the failure.\n",
    "\n",
    "```python\n",
    "# ... more code above..\n",
    "\n",
    "for num in [0, 1000000, -10]:\n",
    "  with self.subTest(num):\n",
    "\n",
    "# ... more code below ....\n",
    "```\n",
    "Optionally, we can give our subtests an argument for better readability of the error messages."
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
